- name: Installing drivers
  community.general.pacman:
    name:
      - mesa
      - lib32-mesa
      - vulkan-radeon
      - lib32-vulkan-radeon
      - vulkan-icd-loader
      - lib32-vulkan-icd-loader
      - mesa-vdpau
      - libva-mesa-driver
      - lib32-libva-mesa-driver
      - lib32-mesa-vdpau
