- name: Check if Chaotic-AUR is installed already
  stat:
    path: /etc/pacman.d/chaotic-mirrorlist
  register: caur_exists

- name: Retrieve Chaotic-AUR master key and sign it
  shell: pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com && pacman-key --lsign-key 3056513887B78AEB
  when: caur_exists.stat.exists | default(true) == false

- name: Install Chaotic-AUR keyring and mirrorlist
  pacman:
    name:
      - https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst
      - https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst
  when: caur_exists.stat.exists | default(true) == false

- name: add repo in pacman
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    block: |
      [chaotic-aur]
      Include = /etc/pacman.d/chaotic-mirrorlist
