- name: Mount the drive
  ansible.posix.mount:
    path: /mnt/Data
    src: UUID="{{ uuid }}"
    fstype: ext4
    state: mounted

- name: Change Data folder persmissions
  ansible.builtin.file:
    path: /mnt/Data
    owner: joe
    group: joe

- name: Create symlinks
  ansible.builtin.file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: joe
    group: joe
    state: link
  loop:
    - src: /mnt/Data/Audiobooks
      dest: /home/joe/Audiobooks
    - src: /mnt/Data/Videos
      dest: /home/joe/Videos
  become_user: joe
