- name: Installing git and utilities
  community.general.pacman:
    name:
      - git
      - lazygit
    state: present

- name: Add settings to ~/.gitconfig
  community.general.git_config:
    name: user.name
    scope: global
    value: joe
  become_user: joe

- name: Add settings to ~/.gitconfig
  community.general.git_config:
    name: user.email
    scope: global
    value: joenikushimi@protonmail.com
  become_user: joe
