- name: Install pomo
  kewlfft.aur.aur:
    use: paru
    name:
      - pomo
  become: true
  become_user: aur_builder

- name: Copy pomo data
  ansible.builtin.copy:
    src: '{{ backup_folder }}/pomo'
    dest: /home/joe/.local/share/pomo
    owner: joe
    group: joe
